name: CI UWP

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore packages
      run: msbuild -t:restore

    - name: Debug Build UWP app
      run: msbuild
      
    - name: VSTest
      run: vstest.console.exe .\IATest\bin\Debug\IATest.dll
